DicomExtract
BenediktHeinrichs/metadataextractor pull request #8
Opened 2024-03-25 12:59 UTC by catgonzftw1

I attempted to add code that extracts from a DICOM file.

2024-03-25 13:03 UTC, catgonzftw1 commented
```
def extract_dicom_metadata(found_files: list) -> dict:
    dicom_metadata = {}  # Initialize the metadata dictionary
    
    for file_name in found_files:
        if file_name.lower().endswith('.dcm'):
            ds = pydicom.dcmread(file_name)
            for elem in ds.iterall():
                if elem.tag.is_private:
                    continue  # Skip private tags
                tag_str = str(elem.tag)
                value = elem.value
                if isinstance(value, pydicom.valuerep.DSfloat):
                    value = float(value)
                dicom_metadata[tag_str] = value

    return dicom_metadata

dicom_metadata = extract_dicom_metadata(found_files)

```

I think the above is the pertinent code. It used the list of found files retrieved by scan_directory()

```
def scan_directory(directory: str, file_patterns: list[str]) -> list:
    file_list = []
    for pattern in file_patterns:
        for file in Path(directory).rglob(pattern):
            if file.is_file():
                file_list.append(file.as_posix())
    return file_list

directory = r"C:\Cat\10-19 CRC_1382\13 sarah_preclinical_data"  # Use 'r' prefix to treat backslashes as literal characters
file_patterns = ["*.dcm", "*.mct", "*.parameters"]  # Update with your desired patterns
found_files = scan_directory(directory, file_patterns)
print(found_files)
```

2024-04-10 09:09 UTC, BenediktHeinrichs requested changes
Hey @catgonzftw1, I reviewed your changes. Still needs a bit of work, feel free to contact me if something is unclear.

2024-04-10 09:09 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/IDataExtract.py
> +        self.mimeTypes["concrete"] = ["text/csv", "text/xml", "application/json", "dcm"]
Please remove that from the default, I don't think this is appropriate as a default value (and won't be necessary for your case).

2024-04-10 09:09 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/ParameterExtract.py
> +class mCTExtract(IDataExtract):
This seems to be obsoleted by `DicomExtract`, so please remove that file.

2024-04-10 09:09 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/mCTExtract.py
> +class mCTExtract(IDataExtract):
This seems to be obsoleted by `DicomExtract`, so please remove that file.

2024-04-10 09:09 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/DicomExtract.py
> +        for attribute in attributes.keys():
you never define any attribute, you should make use of dicom_metadata here instead of attributes

2024-04-10 09:09 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/DicomExtract.py
> +import pydicom
please add pydicom to the [requirements.txt](https://github.com/BenediktHeinrichs/metadataextractor/blob/main/requirements.txt)

2024-04-10 09:09 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/DicomExtract.py
> +class DicomExtract(IDataExtract):
Make sure to add `DicomExtract` to the following list to ensure it properly working: https://github.com/BenediktHeinrichs/metadataextractor/blob/main/defaultConfigs.py#L73

2024-04-10 12:46 UTC, catgonzftw1 reviewed
removed the mCT and parameter extraction files

2024-04-10 12:49 UTC, catgonzftw1 reviewed
Removed the default value as requested

2024-04-10 12:57 UTC, catgonzftw1 reviewed
removed undefined attribute parameter

2024-04-10 12:58 UTC, catgonzftw1 commented
@BenediktHeinrichs I made changes as you noted. Please let me know if it still needs something changed. I can give it another shot :)

2024-04-10 14:15 UTC, BenediktHeinrichs requested changes
@catgonzftw1 I think you missed some comments. Let's talk about this tomorrow.

2024-04-10 14:15 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/DicomExtract.py
> +import pydicom
This has not been resolved

2024-04-10 14:15 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/DicomExtract.py
> +class DicomExtract(IDataExtract):
This has not been resolved

2024-04-11 06:59 UTC, catgonzftw1 commented
@BenediktHeinrichs I was able to edit those files and create pull requests for the unfinished changes. Please let me know if it looks correct :)

2024-04-11 14:48 UTC, catgonzftw1 reviewed
Removed files and made the requested changes into one pull request

2024-04-12 07:13 UTC, catgonzftw1 commented
@BenediktHeinrichs I moved all the changes into this pull request but when I ran the file it throws an error in the first line

`from .IDataExtract import IDataExtract`

The codespace suggested I make a virtual environment which I did but still get the import error:

`ImportError: attempted relative import with no known parent package`

2024-04-12 11:40 UTC, BenediktHeinrichs requested changes
@catgonzftw1 I provided some additional feedback. Please make sure to run & test the code before requesting another review. E.g., you can do this by executing python pipeline_runner.py & checking the output folder afterwards.

The file also isn't meant to run individually.

2024-04-12 11:40 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/DicomExtract.py
> +        self.mimeTypes["concrete"] = ["application/dcm"]
Add "application/dicom" as the mimetype

2024-04-12 11:40 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/DicomExtract.py
> +        dicom_metadata = pydicom.dcmread(file)
Change `file` to `fileInfo["file"]`

2024-04-12 11:40 UTC, BenediktHeinrichs commented on MetadataExtractor/Extractors/Data/DicomExtract.py
> +        dicom_metadata = pydicom.dcmread(file)
On parsing, I get the following error, please check why this is the case & resolve it: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pydicom/dataset.py", line 2283, in __setitem__
    key = Tag(key)
  File "/usr/local/lib/python3.10/site-packages/pydicom/tag.py", line 122, in Tag
    raise ValueError(
ValueError: Unable to create an element tag from '(0008, 0008)': unknown DICOM element keyword or an invalid int
```

2024-04-16 08:07 UTC, catgonzftw1 commented
@BenediktHeinrichs I made some changes and tested it. I think it's working now.

2024-04-24 13:39 UTC, BenediktHeinrichs commented
@catgonzftw1 extraction seems to work now. Is this what you envisoned?

![image](https://github.com/BenediktHeinrichs/metadataextractor/assets/49311227/d4e4b914-7eab-482c-a52a-5eba3711005f)

If yes, just briefly notify me and I'll merge this.

2024-04-24 13:41 UTC, BenediktHeinrichs approved these changes

2024-04-24 13:47 UTC, merged